site_name: Cancer Prediction
site_url: https://github.com/camillabillari/packaging-publishing-cgb47
repo_url: https://github.com/camillabillari/packaging-publishing-cgb47
nav:
  - Home: index.md
  - cancer-prediction:
    - cancer model: src/cancer_prediction_cgb47/cancer_model.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for file changes
